# Exercises

In [19]:
# numpy for vectorized array operations
import numpy as np

# pandas for proper tabular manipulation
import pandas as pd

Using the repo setup directions, setup a new local and remote repository named statistics-exercises. The local version of your repo should live inside of ~/codeup-data-science. This repo should be named statistics-exercises

Do your work for this exercise in either a python file named simulation.py or a jupyter notebook named simulation.ipynb.

In [38]:
np.random.seed(123)
n_trials = 100_000

### How likely is it that you roll doubles when rolling two dice?

In [39]:
#setup
outcomes = [1,2,3,4,5,6]
n_dice = 2

In [40]:
#roll the dice aka simulations
rolls = np.random.choice(outcomes, (n_trials, n_dice))
rolls

array([[6, 3],
       [5, 3],
       [2, 4],
       ...,
       [5, 5],
       [5, 4],
       [4, 6]])

In [41]:
rolls[:,0] #rows, columns

array([6, 5, 2, ..., 5, 5, 4])

In [42]:
rolls[:,1] #rows, columns

array([3, 3, 4, ..., 5, 4, 6])

In [43]:
rolls[:,0] == rolls[:,1]

array([False, False, False, ...,  True, False, False])

In [51]:
rolls.T

array([[6, 5, 2, ..., 5, 5, 4],
       [3, 3, 4, ..., 5, 4, 6]])

In [52]:
rolls.T[0]

array([6, 5, 2, ..., 5, 5, 4])

In [53]:
rolls.T[1]

array([3, 3, 4, ..., 5, 4, 6])

In [54]:
#find doubles
doubles = rolls[:,0] == rolls[:,1]
doubles

array([False, False, False, ...,  True, False, False])

In [55]:
doubles.sum()

16497

In [57]:
n_trials

100000

In [58]:
len(doubles)

100000

In [59]:
doubles

array([False, False, False, ...,  True, False, False])

In [60]:
doubles.sum() / len(doubles)

0.16497

In [61]:
doubles.mean() #short way of doing line above

0.16497

If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [23]:
outcomes = ['h', 't']
n_coins = 8

In [24]:
flips = np.random.choice(outcomes, (n_trials, n_coins))
flips

array([['h', 't', 'h', ..., 'h', 'h', 't'],
       ['t', 'h', 't', ..., 't', 'h', 't'],
       ['h', 't', 't', ..., 'h', 't', 't'],
       ...,
       ['h', 'h', 'h', ..., 't', 't', 'h'],
       ['t', 'h', 'h', ..., 't', 'h', 'h'],
       ['h', 'h', 't', ..., 't', 'h', 'h']], dtype='<U1')

In [25]:
heads_per_sim = (flips == 'h').sum(axis=1)
heads_per_sim

array([6, 3, 4, ..., 5, 5, 6])

In [26]:
(heads_per_sim == 3).mean()

0.21562

In [27]:
(heads_per_sim > 3).mean()

0.63886

### There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [62]:
outcomes = ['ds', 'wd', 'wd', 'wd']
n_billboards = 2

In [63]:
# one way of defining
billboards = np.random.choice(outcomes, (n_trials, n_billboards))
billboards

array([['wd', 'wd'],
       ['wd', 'wd'],
       ['wd', 'wd'],
       ...,
       ['wd', 'wd'],
       ['wd', 'wd'],
       ['wd', 'wd']], dtype='<U2')

In [64]:
#another way of defining our billboards
outcomes = ['ds', 'wd']

In [65]:
billboards = np.random.choice(outcomes, (n_trials, n_billboards), 
                              p=[0.25,0.75]) #more programmatic way
billboards

array([['wd', 'wd'],
       ['wd', 'ds'],
       ['wd', 'ds'],
       ...,
       ['ds', 'wd'],
       ['ds', 'wd'],
       ['wd', 'wd']], dtype='<U2')

In [66]:
ds_billboards = (billboards == 'ds').sum(axis=1)
ds_billboards

array([0, 1, 1, ..., 1, 1, 0])

In [67]:
(ds_billboards == 2).mean()

0.06225

In [ ]:
# random.random method worked for Kelsey and Nomer

### 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [50]:
μ = 3 
σ = 1.5
n_days = 5

In [52]:
poptarts_purchased_daily = np.random.normal(μ, σ, (n_trials, n_days))
poptarts_purchased_daily

array([[3.12664333, 1.878936  , 2.96322342, 2.93561674, 2.40733566],
       [3.5390844 , 3.51875229, 3.30861337, 6.74992752, 3.53718038],
       [3.5237069 , 1.67216539, 3.76697203, 4.86862779, 3.43352484],
       ...,
       [3.07100981, 4.03451335, 2.63755884, 3.97050888, 1.09070429],
       [0.60841487, 4.74155473, 3.79632031, 4.56734109, 5.15113083],
       [3.97233054, 3.87732036, 4.19280629, 3.40632919, 1.67284563]])

In [54]:
poptarts_purchased_weekly = poptarts_purchased_daily.sum(axis=1)
poptarts_purchased_weekly

array([13.31175514, 20.65355795, 17.26499696, ..., 14.80429518,
       18.86476183, 17.121632  ])

In [61]:
# at least one poptart left so I can but it
(17 - poptarts_purchased_weekly) >= 1    # > is fine compared to >= because the chance it's a whole number is rare

array([ True, False, False, ...,  True, False, False])

In [62]:
((17 - poptarts_purchased_weekly) >= 1).mean()

0.6179

### 5. Compare Heights

* Men have an average height of 178 cm and standard deviation of 8cm.

* Women have a mean of 170, sd = 6cm.

* Since you have means and standard deviations, you can use np.random.normal to generate observations.

* If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [63]:
mean_men = 178
sd_men = 8

mean_women = 170
sd_women = 6

In [64]:
heights_men = np.random.normal(mean_men, sd_men, n_trials)
heights_men

array([175.58619908, 176.94212538, 180.56431691, ..., 178.58120539,
       168.16285606, 186.44281336])

In [65]:
heights_women = np.random.normal(mean_women, sd_women, n_trials)
heights_women

array([177.06055742, 169.92477933, 175.5139039 , ..., 172.25161538,
       183.56471524, 166.37659483])

In [68]:
heights_women > heights_men

array([ True, False, False, ..., False,  True, False])

In [67]:
(heights_women > heights_men).mean()

0.2154

### 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 

In [69]:
outcomes = ['p', 'f']
probs_outcomes = [249/250, 1/250]
n_students = 50

In [70]:
installs = np.random.choice(outcomes, (n_trials, n_students), 
                 p=probs_outcomes)
installs

array([['p', 'p', 'p', ..., 'p', 'p', 'p'],
       ['p', 'p', 'p', ..., 'p', 'p', 'p'],
       ['p', 'p', 'p', ..., 'p', 'p', 'p'],
       ...,
       ['p', 'p', 'p', ..., 'p', 'p', 'p'],
       ['p', 'p', 'p', ..., 'p', 'p', 'p'],
       ['p', 'p', 'p', ..., 'p', 'p', 'p']], dtype='<U1')

In [71]:
total_fails = (installs == 'f').sum(axis=1)
total_fails

array([0, 0, 0, ..., 0, 1, 0])

In [72]:
(total_fails == 0).mean()

0.81923

### 100 students?

In [73]:
n_students = 100

installs = np.random.choice(outcomes, (n_trials, n_students), 
                 p=probs_outcomes)

total_fails = (installs == 'f').sum(axis=1)

(total_fails == 0).mean()

0.67083

#### What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [74]:
installs == 'f'

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [75]:
# update to 150 students
n_students = 150

installs = np.random.choice(outcomes, (n_trials, n_students), 
                 p=probs_outcomes)

total_fails = (installs == 'f').sum(axis=1)

#update to at least one failure
(total_fails > 0).mean()

0.45171

#### How likely is it that 450 students all download anaconda without an issue?

In [76]:
# update to 450 students
n_students = 450

installs = np.random.choice(outcomes, (n_trials, n_students), 
                 p=probs_outcomes)

total_fails = (installs == 'f').sum(axis=1)

# update to 0 failures
(total_fails == 0).mean()

0.16506

### 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [80]:
p_truck = 0.7
n_days = 3

In [83]:
is_truck_question = np.random.random((n_trials, n_days))
is_truck_question

array([[0.06188714, 0.75746495, 0.2187423 ],
       [0.89529707, 0.50188288, 0.66007328],
       [0.08516897, 0.28033745, 0.74838753],
       ...,
       [0.46732858, 0.39365545, 0.60106292],
       [0.6812133 , 0.6294546 , 0.36646324],
       [0.27605962, 0.49489929, 0.82130275]])

In [85]:
yes_truck = is_truck_question < p_truck
yes_truck

array([[ True, False,  True],
       [False,  True,  True],
       [ True,  True, False],
       ...,
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False]])

In [86]:
# how many times there is no truck there
(yes_truck.sum(axis=1) == 0).mean()

0.02601

#### How likely is it that a food truck will show up sometime this week?

In [88]:
n_days = 5

In [89]:
is_truck_question = np.random.random((n_trials, n_days))

yes_truck = is_truck_question < p_truck

# update to show at least one truck shows up this week
(yes_truck.sum(axis=1) >=1).mean()

0.99754

### 8. If 23 people are in the same room, what are the odds that two of them share a birthday?

In [97]:
n_people = 23
outcomes = list(range(1, 366))

In [100]:
birthdays = np.random.choice(outcomes, (n_trials, n_people))
birthdays

array([[345, 156, 195, ..., 169, 109, 197],
       [200, 249, 270, ...,   6,  55, 237],
       [321, 131,  78, ..., 322,  51, 198],
       ...,
       [ 85, 200, 211, ..., 182, 193,  33],
       [208, 312, 162, ...,  90, 262, 204],
       [132,  52, 150, ..., 274, 141,  23]])

In [102]:
birthdays = pd.DataFrame(birthdays)
birthdays.head()

0    1    2    3    4    5    6    7    8    9   ...   13   14   15   16  \
0  345  156  195  160  279  292  220  289  320  129  ...  246  351  326  302   
1  200  249  270  260  132  137  300   35   81   36  ...  318  116  259  251   
2  321  131   78  331  247  130    2  156  227   74  ...  353   32  263  282   
3  191  328  255  252  243  300  144   51  194  317  ...  270   24  100  117   
4  296  128  298   56  359  210  165  241  132  181  ...  339   97    6  185   

    17   18   19   20   21   22  
0  202  189   95  169  109  197  
1  221  128  166    6   55  237  
2  235  238  269  322   51  198  
3  349  167   78  282   58  208  
4  158  148   30    8  250  127  

[5 rows x 23 columns]

In [104]:
# how many unique values exist for each row

birthdays.nunique(axis = 1)

0        23
1        23
2        22
3        23
4        23
         ..
99995    23
99996    22
99997    23
99998    22
99999    23
Length: 100000, dtype: int64

In [105]:
birthdays.nunique(axis = 1) < n_people

0        False
1        False
2         True
3        False
4        False
         ...  
99995    False
99996     True
99997    False
99998     True
99999    False
Length: 100000, dtype: bool

In [106]:
(birthdays.nunique(axis = 1) < n_people).mean()

0.50711

`Be sure to add, commit, and push your work.`

### What if it's 20 people? 

In [108]:
n_people = 20

birthdays = np.random.choice(outcomes, (n_trials, n_people))
birthdays = pd.DataFrame(birthdays)

(birthdays.nunique(axis = 1) < n_people).mean()

0.41297

### 40?

In [109]:
n_people = 40

birthdays = np.random.choice(outcomes, (n_trials, n_people))
birthdays = pd.DataFrame(birthdays)

(birthdays.nunique(axis = 1) < n_people).mean()

0.89036

#### Bonus Exercises

* Mage Duel (link in book)

* Chuck a Luck (link in book)